In [3]:
!git status


On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	Untitled.ipynb
	dataVenv/trial.py

nothing added to commit but untracked files present (use "git add" to track)


In [2]:
!git status


On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	Untitled.ipynb
	dataVenv/trial.py

nothing added to commit but untracked files present (use "git add" to track)


In [4]:
!git add .


In [5]:
!git commit -m "this"

[master 8f5c7ec] this
 3 files changed, 96 insertions(+)
 create mode 100644 .ipynb_checkpoints/Untitled-checkpoint.ipynb
 create mode 100644 Untitled.ipynb
 create mode 100644 dataVenv/trial.py


In [6]:
!git push


To https://github.com/kasasa22/DataAnalysis.git
   2c709f9..8f5c7ec  master -> master


In [1]:
import pandas as pd

In [2]:
tup = (4,5,6)
tup


(4, 5, 6)

In [7]:
#DATA STRUCTURES
#Tuples
tuple([4,0,2])

(4, 0, 2)

In [20]:
#nested tuple
tup=((4,3,4),(2,3,4))
tup[0][2]



4

In [24]:
tup= tuple(['kasasa',[1,2],False,'Trevor'])
tup[2]

False

In [25]:
tup[1][0]

1

In [26]:
tup[2] =True

TypeError: 'tuple' object does not support item assignment

In [27]:
tup[1][1]=3

In [28]:
tup

('kasasa', [1, 3], False, 'Trevor')

In [29]:
#LIST
ls =["This","is","Africa"]
ls

['This', 'is', 'Africa']

In [30]:
ls[2]="USA"

In [32]:
ls

['This', 'is', 'USA']

In [34]:
ls.index("USA")

2

In [37]:
ls1=list(ls)
ls1

['This', 'is', 'USA']

In [40]:
d1={1:"kasasa","2":"sarah","3":"trevor"}
d1

{1: 'kasasa', '2': 'sarah', '3': 'trevor'}

In [42]:
d1[1]

'kasasa'

In [45]:
d2 = {(1, 2, 3): ['this', 'that', 'those']}
print(d2)


{(1, 2, 3): ['this', 'that', 'those']}


In [47]:
d2 = {True:(1,2,3) }
print(d2)


{True: (1, 2, 3)}


In [51]:
d2

{True: (1, 2, 3)}

In [52]:
ls=[1,2,3,'trevor','cdd']
ls

[1, 2, 3, 'trevor', 'cdd']

In [53]:
s='string'

In [54]:
s

'string'

In [55]:
s[0]

's'

In [57]:
s[0]='w'

TypeError: 'str' object does not support item assignment

In [60]:
key_list = ['a', 'b', 'c']
value_list = [1, 2, 3]
mapping={}
for key, value in zip(key_list,value_list):
    mapping[key] =value
mapping

{'a': 1, 'b': 2, 'c': 3}

In [64]:
tuples=zip(range(10), reversed(range(10)))
tuples

In [65]:
mapping = dict(tuples)

In [66]:
mapping

{0: 9, 1: 8, 2: 7, 3: 6, 4: 5, 5: 4, 6: 3, 7: 2, 8: 1, 9: 0}

In [67]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Untitled.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	dataStructures.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [68]:
!git add .

In [69]:
!git push 

Everything up-to-date


In [70]:
def function(x,y):
    return(x*y)

In [71]:
function(2,3)

6

In [78]:
def function(x):
    if x % 2 == 0:
        return 'even'
    else:
        return 'odd'


In [79]:
function(9)

'odd'

In [80]:
!git add .

In [82]:
!git commit -a -m "python essecials"

[master efcd90b] python essecials
 2 files changed, 780 insertions(+), 1 deletion(-)
 create mode 100644 dataStructures.ipynb


In [83]:
!git push

To https://github.com/kasasa22/DataAnalysis.git
   8f5c7ec..efcd90b  master -> master


In [84]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Untitled.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [1]:
x = 45
x

45

In [1]:
import numpy as np

In [5]:
arr=np.arange(100_000_00)
arr

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [7]:
ls=[[1,2,3],[3,4,5],[6,7,8]]
ls

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [9]:
np.array(ls)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
data=np.array(ls)

In [11]:
data

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
data.shape

(3, 3)

In [14]:
a = np.array([1, 2, 3])
b=np.array([2,3,4])
c=a+b
c

array([3, 5, 7])

In [15]:
d=a*c
d

array([ 3, 10, 21])

In [16]:
d.shape

(3,)

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
array=np.array([1,2,3],dtype=np.float64)
array

array([1., 2., 3.])

In [25]:
array=np.array([1,2,3],dtype=np.int64)
array

array([1, 2, 3], dtype=int64)

In [29]:
array.astype(np.int64)


array([1, 2, 3], dtype=int64)

In [30]:
array.astype(np.float64)


array([1., 2., 3.])

In [35]:
arr3= np.array([[[1,2,3],[3,4,5]],[[2,3,4],[5,6,7]]])
arr3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[2, 3, 4],
        [5, 6, 7]]])

In [40]:
a

array([1, 2, 3])

In [41]:
arr = np.array([10, 20, 30, 40, 50])


In [42]:
bool_arr = arr > 25

In [43]:
filtered_arr = arr[bool_arr]

In [44]:
filtered_arr

array([30, 40, 50])